FROM node:16.14.0-alpine3.14 AS build
WORKDIR /app
COPY ./kanban-frontend/package.json ./kanban-frontend/package-lock.json ./
RUN npm install
COPY ./kanban-frontend/ .
RUN npm run build

FROM node:16.14.0-alpine3.14
WORKDIR /app
COPY --from=build /app/build ./
RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-p", "3000", "-s", "."]