# Use an official Golang runtime as a parent image
FROM golang:1.17.2-alpine3.14

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./kanban-backend /app

# Build the backend application
RUN go build -o kanban-board-backend .

# Install SQLite
RUN apk add sqlite

# Create a new SQLite database
RUN touch tasks.db

# Make the container's port 8080 available to the outside world
EXPOSE 8080

# Run the backend application when the container starts
CMD ["./kanban-board-backend"]
