version: '3'

services:
  backend:
    build: .
    dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite3://tasks.db
  db:
    image: "docker.io/library/postgres:14-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tasks
    volumes:
      - db-data:/var/lib/postgresql/data
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    depends_on:
      - backend

volumes:
  db-data:
